default: ping_otelsender udping_otelsender

udping_otelsender: udping_otelsender.go
	go build udping_otelsender.go
	cp udping_otelsender ../bin

ping_otelsender: ping_otelsender.go
	go build ping_otelsender.go
	cp ping_otelsender ../bin
