#!/usr/bin/python3

import requests
import getopt
import sys
import os
import json
import time
import signal

arglist = sys.argv[1:]
options = "vc:h:p:k:?"

controller = ''
verbose = False
polling_interval = 10
keepalive_interval = 10
hostname = ''

children = {}


def checkForOrphans():
    signatures = list(children.keys())
    dosync = False
    ret = 0
    for signature in signatures:
        (pid, exit) = os.waitpid(children[signature]['pid'], os.WNOHANG)
        if pid > 0:
            print ("Detected terminated child %d"%pid)
            del children[signature]
            ret = ret + 1
    return ret


def launchPing(signature, params):
    print ("Launching child %s"%signature)
    pid = os.fork()
    if (pid > 0):
        print ("Launched child with pid %d"%pid)
        print (params)
        children[signature] = params
        children[signature]['pid'] = pid
        return

    elif (pid == 0):
        signal.signal(signal.SIGINT, signal.SIG_DFL)
#        print (["./pinger", "pinger", "-a", params['peer_ip'], "-i", str(int(params['mesh_delay_ms'])), "-r", str(int(params['mesh_reporting_interval_s'])), "-m", params["mesh_name"]])
#        os.execl("./pinger", "./pinger", "-a", params['peer_ip'], "-i", str(int(params['mesh_delay_ms'])), "-r", str(int(params['mesh_reporting_interval_s'])), "-m", params["mesh_name"])
        print ("ping %s | ./ping_otelsender -from_host=%s -to_host=%s -mesh=%s"%(params['peer_ip'], hostname, params['peer_ip'], params['mesh_name']))
        os.system ("ping %s | ./ping_otelsender -from_host=%s -to_host=%s -mesh=%s"%(params['peer_ip'], hostname, params['peer_ip'], params['mesh_name']))
        sys.exit()

def killPing(signature):
    print ("Killing child %s"%signature)
    print (children[signature])
    os.kill(children[signature]['pid'], signal.SIGTERM)
    del children[signature]

def update(controller, hostname, targetList):
    print ("Connecting to %s as %s"%(controller, hostname))
    try:
        r = requests.get("http://%s/q/peers?hostname=%s"%(controller, hostname));
    except:
        print ("Controller down - continuing with existing config")
        return targetList
    if r.status_code == 200:
        return r.json()
    return targetList

def keepalive (controller, hostname):
    try:
        u = requests.get("http://%s/r/keepalive?hostname=%s"%(controller, hostname));
    except:
        print ("Controller down - no keepalive sent")
        pass
    return

def synchronize (targetList):
    targetChildren = {}
    for params in targetList:
        signature = "%s.%s:%s.%s:%s"%( params['mesh_name'], params['local_hostname'], params['local_ip'], params['peer_hostname'], params['peer_ip'])
        targetChildren[signature] = True
        if (signature in children) and (params['mesh_delay_ms'] != children[signature]['mesh_delay_ms']):
            killPing(signature)
        if (signature not in children):
            launchPing(signature, params)
    for signature in list(children.keys()):
        if signature not in targetChildren:
            killPing (signature)

def shutdown(sig, frame):
    print ("Interrupt detected.  Cleaning up ...")
    for signature in list(children.keys()):
        killPing (signature)
    print ("Done cleaning up.  Exiting")
    sys.exit()

def usage():
    print("Usage: udping_controller -c <controller> -h <hostname> [-p polling_interval] [-k keepalive_interval] [-v] [-?]")
    print("   -c: Central controller (host:port)")
    print("   -p: Polling interval in seconds (default: 10)")
    print("   -k: Keepalive interval in seconds (default: 10)")
    print("   -h: Hostname")
    print("   -v: Verbose")
    print("   -?: Print this text")
    sys.exit()

try:
    arguments, values = getopt.getopt(arglist, options)
    for curarg,curval in arguments:
        if curarg == "-v":
            verbose = True
        elif curarg == "-c":
            controller = curval
        elif curarg == "-h":
            hostname = curval
except Exception as err:
    print("Error: %s\n"%str(err))
    usage()

if controller == '':
    usage()
if hostname == '':
    usage()

signal.signal(signal.SIGINT, shutdown)

now = 0

targetList = update (controller, hostname, [])
while (True):
    if not (now % polling_interval):
        targetList = update (controller, hostname, targetList)
        synchronize (targetList)
    if not (now % keepalive_interval):
        keepalive (controller, hostname)
    if checkForOrphans() > 0:
        synchronize (targetList)
    time.sleep(1)
    now = int (time.time())


