FROM node:26

WORKDIR /usr/src/app

RUN apt update
RUN apt install -y net-tools
RUN apt install -y iputils-ping
RUN apt install -y sqlite3
RUN apt update
RUN ln -sf /usr/share/zoneinfo/PST8PDT /etc/localtime
RUN npm install -g npm@12.0.2
RUN npm install express@4
RUN npm install sqlite3 --ignore-scripts=false
RUN npm install-scripts approve sqlite3
RUN npm uninstall sqlite3
RUN npm install sqlite3 --ignore-scripts=false


COPY database.js .
COPY udping.js .
COPY udping.db .
COPY udping.sql .
COPY public public

CMD [ "node", "udping.js"]
#CMD [ "bash" ]
